### ISSUE TITLE
Notifications are sent to disabled users

### ISSUE THREAD

**Issue by funkycram** [staxDB/humhub-modules-announcements#51]
Is a user has the status "disabled" (in MySQL table "user", the field "status" has the value 0 if the user is disabled), he cannot access the platform and doesn't receive any notifications any more.

But a content published with this announcement module sends notification emails to everybody, including disabled users.

**Comment by funkycram** [comment]
This should fix the problem : https://github.com/staxDB/humhub-modules-announcements/compare/master...funkycram:patch-2

**Comment by staxDB** [comment]
Should be fixed with v0.3.6
